remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme

title: Ricardo Elisiário
description: 💙🤎
logo: images/Ricardo.jpg
url:
baseurl:
email: 
github_username: rimedelis
twitter_username: rimedelis
# show_downloads: [true or false to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]