theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Ricardo Elisiário
description: My personal website
logo: _includes/MoRi.jpg
url:
baseurl:
email: 
github_username: rimedelis
twitter_username: 
# show_downloads: [true or false to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]